[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_ws = "${BASE_WSS_URL}"
megaeth = "${MEGAETH_RPC_URL}"
megaeth_ws = "${MEGAETH_WSS_URL}"

[profile.default.vyper]
path = ".venv/bin/vyper"
