[megaeth]
chain = "megaeth"
chain_id = 4326
contraparty = "0x0000000000000000000000000000000000000000"
deployed_at_unix = 0

[megaeth.factories]
prism = "0x0000000000000000000000000000000000000000"
kumbaya = "0x0000000000000000000000000000000000000000"

[megaeth.quoters]
prism = "0x0000000000000000000000000000000000000000"
kumbaya = "0x0000000000000000000000000000000000000000"

[megaeth.amms]
prism_uniswap_v3 = "0x0000000000000000000000000000000000000000"
kumbaya_uniswap_v3 = "0x0000000000000000000000000000000000000000"
canonic_weth_usdm = "0x0000000000000000000000000000000000000000"
canonic_btcb_usdm = "0x0000000000000000000000000000000000000000"
canonic_usdt0_usdm = "0x0000000000000000000000000000000000000000"

[megaeth.canonic_maobs]
weth_usdm = "0x23469683e25b780DFDC11410a8e83c923caDF125"
btcb_usdm = "0xaD7e5CBfB535ceC8d2E58Dca17b11d9bA76f555E"
usdt0_usdm = "0xDf1576c3C82C9f8B759C69f4cF256061C6Fe1f9e"

[megaeth.pools.prism_weth_usdm]
address = "0xC2FaC0B5B6C075819E654bcFbBBCda2838609d32"
fee = 3000
token0 = "0x4200000000000000000000000000000000000006"
token1 = "0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7"

[megaeth.pools.kumbaya_weth_usdm]
address = "0x587F6eeAfc7Ad567e96eD1B62775fA6402164b22"
fee = 3000
token0 = "0x4200000000000000000000000000000000000006"
token1 = "0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7"

[megaeth.pools.kumbaya_weth_usdt0]
address = "0x2809696F2e42eB452C32C3d0A2Dc540858C14125"
fee = 3000
token0 = "0x4200000000000000000000000000000000000006"
token1 = "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb"

[megaeth.pools.kumbaya_btcb_usdm]
address = "0xc1838B7807e5bd4D56EA630BA35Ac964CF72c9db"
fee = 3000
token0 = "0xB0F70C0bD6FD87dbEb7C10dC692a2a6106817072"
token1 = "0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7"

[megaeth.pools.kumbaya_usdt0_usdm]
address = "0x6c8E5D463a2473b1A8bcd87e1cEA2724203A1D8f"
fee = 100
token0 = "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb"
token1 = "0xFAfDdbb3FC7688494971a79cc65DCa3EF82079E7"
