[base]
chain = "base"
chain_id = 8453
contraparty = "0x0000000000000000000000000000000000000000"
v3_quoter = "0x0000000000000000000000000000000000000000"
deployed_at_unix = 0

[base.amms]
uniswap_v3 = "0x0000000000000000000000000000000000000000"
uniswap_v2 = "0x0000000000000000000000000000000000000000"
aerodrome = "0x0000000000000000000000000000000000000000"

[base.pools.uniswap_v3_weth_usdc_500]
address = "0x0000000000000000000000000000000000000000"
fee = 500

[base.pools.uniswap_v3_weth_usdc_3000]
address = "0x0000000000000000000000000000000000000000"
fee = 3000

[megaeth]
chain = "megaeth"
chain_id = 4326
contraparty = "0x0000000000000000000000000000000000000000"
deployed_at_unix = 0

[megaeth.factories]
prism = "0x0000000000000000000000000000000000000000"
kumbaya = "0x0000000000000000000000000000000000000000"

[megaeth.quoters]
prism = "0x0000000000000000000000000000000000000000"
kumbaya = "0x0000000000000000000000000000000000000000"

[megaeth.amms]
prism_uniswap_v3 = "0x0000000000000000000000000000000000000000"
kumbaya_uniswap_v3 = "0x0000000000000000000000000000000000000000"

[megaeth.pools.prism_weth_usdm]
address = "0xC2FaC0B5B6C075819E654bcFbBBCda2838609d32"
fee = 3000

[megaeth.pools.kumbaya_weth_usdm]
address = "0x587F6eeAfc7Ad567e96eD1B62775fA6402164b22"
fee = 3000
