[megaeth]
chain = "megaeth"
chain_id = 4326
deployed_at_unix = 0

[megaeth.factories]
prism = "0x0000000000000000000000000000000000000000"
kumbaya = "0x0000000000000000000000000000000000000000"

[megaeth.quoters]
prism = "0x0000000000000000000000000000000000000000"
kumbaya = "0x0000000000000000000000000000000000000000"
